# fly.toml app configuration file generated for cron-ingest on 2023-06-15T18:15:58-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "cron-ingest"
primary_region = "yyz"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
